### ISSUE TITLE
64-bit World Editor. Mono sound in 64-bit version.

### ISSUE THREAD

**Issue by tx00100xt** [SamClassicPatch/SuperProject#1]
Привет. Вот пару полезностей.

Рабочий редактор уровней для 64 битной версии: https://github.com/tx00100xt/SeriousSamClassic/commit/ace7de5c7f631dd70d21ebc8dc21e72e1b2e7706
Причина крашей была в некорректном приведении адресов указателей для 64-битной версии.

Стерео звук в 64-битной версии:
https://github.com/tx00100xt/SeriousSamClassic/blob/main/SamTFE/Sources/Engine/Sound/SoundMixer.cpp#L709
При переводе кода с ассемблера пропустили одну команду MMX, В результате микшируется только один канал.
`    slRightSample = pswSrcBuffer[(fixRightOfs>>15)+1]; // fixed`
`    slNextSample  = pswSrcBuffer[(fixRightOfs>>15)+3]; // fixed`

Можно ещё посмотреть полезности здесь:
https://github.com/tx00100xt/SeriousSamClassic/blob/main/CHANGELOG.md
https://github.com/tx00100xt/SeriousSamClassic-VK/blob/main/CHANGELOG.md

С Наступающим!

**Comment by DreamyCecil** [comment]
Это всё, конечно, полезно, но у меня нет доступа к коду самого движка. Всё делается поверх него. Звук я точно не смогу исправить, если не перепишу весь звуковой движок в принципе (хотя я даже не припомню проблем со звуком в классике).

А редактор у меня уже работает и не работал он по другим причинам. Правки, как я понимаю, касаются кастов переменных для MFC, но у меня проблем с MFC не было, потому что используется тот же старый MFC, что и у движков ~2001 года.

**Comment by tx00100xt** [comment]
Это моя невнимательность :) Думал здесь зеркало проекта, который вы с zcaliptium на ГитЛаб развиваете.  
Я оттуда недавно исправления для lightmap взял, для 64-битной версии.
Глянул проект то другой, хоть и имя одинаковое.
Конечно исправления исключительно для версии 1.10
Ещё раз с Наступающим!
