### ISSUE TITLE
Xbox 360 controller support

### ISSUE THREAD

**Issue by comrade88max** [SamClassicPatch/SuperProject#10]
Is it possible to add support for the xbox 360 gamepad in future updates?
The game already partially supports the xbox 360 controller, but it is impossible to configure it through the game interface, only through configs (*.ctl), all buttons and sticks work except for the triggers.

**Comment by DreamyCecil** [comment]
I've implemented better controller support for the upcoming 1.9 update. If you'd like to test it, you can install a pre-release version now: https://github.com/SamClassicPatch/SuperProject/releases/tag/1.9-pre1

Use new controls presets to setup default controller binds.

**Comment by comrade88max** [comment]
Большое тебе СПАСИБО :)
