### ISSUE TITLE
Error steam_appid.txt

### ISSUE THREAD

**Issue by geckotdf** [SamClassicPatch/SuperProject#13]
Hi!
Im having an issue when try to launch the SeriousSam_Custom.exe
Im using the GoG version of the game, extract the files in a fresh installation but when I try to launch the .exe have this error

Fatal Error
Error reading application id. Please either write it to steam_appid.txt or use the launcher!

The steam_appid.txt it's next to the SeriousSam_Custom.exe in the same folder.

Thanks!

**Comment by DreamyCecil** [comment]
Try disabling connection with Steam by setting this config property in `Data/ClassicsPatch/Config.ini`:
```ini
[Steam]
Enable = 0
```
Or delete `steam_api.dll` from the Bin folder altogether.

**Comment by geckotdf** [comment]
Hi @DreamyCecil thanks both methods works perfect. 
Probably this can be add it to the install instructions  the editing of the Config.ini.

I put this in close condition because it's fixed.
Have a good day.

**Comment by geckotdf** [comment]
Hi @DreamyCecil thanks both methods works perfect. 
Probably this can be add it to the install instructions  the editing of the Config.ini.

I put this in close condition because it's fixed.
Have a good day.
