### ISSUE TITLE
Fullscreen OpenGL forces display to 60Hz

### ISSUE THREAD

**Issue by Q3BFG10K** [SamClassicPatch/SuperProject#2]
This is also problem with the original game, Steamify patches, and Classics Revolution.

Changing **gap_iRefreshRate** just resets the display to windowed 640x480 after restarting the game.

The only work-around is using borderless or windowed mode, or running Direct3D.

**Comment by DreamyCecil** [comment]
I'm afraid I can't fix this. Best thing you can do is try removing all refresh rates from settings other than the desired one and it will force that one instead, since it's picking the lowest refresh rate available. I personally don't know how to do it.
