### ISSUE TITLE
Feature request: anti-aliasing

### ISSUE THREAD

**Issue by Q3BFG10K** [SamClassicPatch/SuperProject#4]
It would be really useful to add SMAA, high quality FXAA, or 4xMSAA into the game.

**Comment by DreamyCecil** [comment]
This seems overly complex since I have limited access to the engine itself. I'll try looking into it but in the mean time you can try forcing anti-aliasing in the graphics panel.

**Comment by DreamyCecil** [comment]
And it seems like this is also impossible to implement; it's just easier to force the GPU to apply specific settings to the game's executable.
