### ISSUE TITLE
World Editor: How to open Terrain Editing?

### ISSUE THREAD

**Issue by YukiXXL** [SamClassicPatch/SuperProject#9]
Hi. I see that there is a somekind of "TerrainEditing" source files inside the "WorldEditor" tree. Is it functional and how to open it?
Thank you.

**Comment by DreamyCecil** [comment]
If you have a terrain entity implemented in a mod or whatnot, you can enter terrain editing mode using R. It's the same editing mode as in 1.10 (including Revolution).

**Comment by YukiXXL** [comment]
Terrain Entity? You mean, terrain primitive? Does this WorldEditor have that Terrain Entity implemented?

**Comment by DreamyCecil** [comment]
If you want to test it out, you can create your own ECL file targeting `CTerrainEntity` from EntitiesMP.

**Comment by YukiXXL** [comment]
Thanks. Got it working. Tho it kinda is useless since it cannot be used on Terrain Primitive. I guess it is used for making heightmaps.

**Comment by DreamyCecil** [comment]
I specifically added a new function in 1.7 for exporting heightmaps from terrain entities that can be reused on terrain primitives. Terrain entities are much better for storing the original high quality data.

![image](https://github.com/SamClassicPatch/SuperProject/assets/21009796/1522f7a1-c28a-4149-895d-88fbdd86dff6)
